### ISSUE TITLE
Go 语言学习

### ISSUE THREAD

**Issue by ChungZH** [ChungZH/My-Plan#2]
Go 语言学习，使用[ Go 入门指南](https://github.com/Unknwon/the-way-to-go_ZH_CN)。

**Comment by ChungZH** [comment]
没有学习，无限期顺延，即暂停。

**Comment by JackEggie** [comment]
想念小猪蹄。

有没有回即刻逛逛的计划呀？

p.s. 我是蛋卷，不知道你还记得我不。

**Comment by ChungZH** [comment]
> 想念小猪蹄。
> 
> 有没有回即刻逛逛的计划呀？
> 
> p.s. 我是蛋卷，不知道你还记得我不。

Hello 蛋卷，快加我微信 `zhong124694738` ！:smile:
